
services:
  mongo1:
    image: mongo:5
    container_name: mongo1
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo1
    networks:
      - mongoCluster
    ports:
      - 27017:27017
    volumes:
      - mongo1data:/data/db

  mongo2:
    image: mongo:5
    container_name: mongo2
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo2
    networks:
      - mongoCluster
    ports:
      - 27018:27017
    volumes:
      - mongo2data:/data/db

  mongo3:
    image: mongo:5
    container_name: mongo3
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo3
    networks:
      - mongoCluster
    ports:
      - 27019:27017
    volumes:
      - mongo3data:/data/db

networks:
  mongoCluster:

volumes:
  mongo1data:
  mongo2data:
  mongo3data:
